import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { Category } from '../src/components/Category';
import { FloatingButton } from '../src/components/Buttons';
import { useHome } from '../src/hooks/useHome';

const Home: NextPage = () => {
  const controller = useHome();

  return (
    <div>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className={styles.pageTitle}>AWARDS 2021</h2>
        <div className={styles.categoriesContainer}>
          {controller.isLoadingBallot ? (
            <div style={{ textAlign: 'center' }}>
              Loading Ballots, please wait...
            </div>
          ) : controller.ballotsError ? (
            <div style={{ textAlign: 'center' }}>
              An Error: {JSON.stringify(controller.ballotsError)}
            </div>
          ) : controller.hasBallots ? (
            controller.ballots.map((ballot) => (
              <Category
                key={ballot.id}
                ballot={ballot}
                onSelectNominee={controller.onSelectNomineeCategory(
                  ballot.id,
                  ballot.title,
                )}
                selectedNomineeCategory={controller.selectedNomineeData.find(
                  (item) => item.categoryId === ballot.id,
                )}
              />
            ))
          ) : (
            <div style={{ textAlign: 'center' }}>No ballots found</div>
          )}
        </div>
        <FloatingButton
          disabled={!controller.hasSelectedNominees}
          title={
            controller.hasSelectedNominees
              ? 'Click to submit your vote'
              : 'Please select at least one nominee'
          }
        >
          SUBMIT BALLOT
        </FloatingButton>
      </main>
    </div>
  );
};

export default Home;
