import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { Category } from '../src/components/Category';
import { FloatingButton } from '../src/components/Buttons';
import { useBallotsGet } from '../src/hooks/useBallotsGet';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const { ballots, isLoadingBallot, ballotsError, hasBallots, getBallots } =
    useBallotsGet();

  useEffect(() => {
    getBallots();
  }, [getBallots]);

  return (
    <div>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className={styles.pageTitle}>AWARDS 2021</h2>
        <div className={styles.categoriesContainer}>
          {isLoadingBallot ? (
            <div style={{ textAlign: 'center' }}>
              Loading Ballots, please wait...
            </div>
          ) : ballotsError ? (
            <div style={{ textAlign: 'center' }}>
              An Error: {JSON.stringify(ballotsError)}
            </div>
          ) : hasBallots ? (
            ballots.map((ballot) => (
              <Category key={ballot.id} ballot={ballot} />
            ))
          ) : (
            <div style={{ textAlign: 'center' }}>No ballots found</div>
          )}
        </div>
        <FloatingButton>Submit Ballot</FloatingButton>
      </main>
    </div>
  );
};

export default Home;
