import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { Category } from '../src/components/Category';
import { FloatingButton } from '../src/components/Buttons';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className={styles.pageTitle}>AWARDS 2021</h2>
        <div className={styles.categoriesContainer}>
          <Category />
          <Category />
        </div>
        <FloatingButton>Submit Ballot</FloatingButton>
      </main>
    </div>
  );
};

export default Home;
